#.github/sync.yml
group:
  # 1st group for sync-up
  - files:
      - source: data/raw_SupplyChain_*.csv
        dest:   data/stage1_raw/raw_SupplyChain_*.csv
  - files:
      - source: data/raw_SupplyChainMap.csv
        dest:   data/stage1_raw/raw_SupplyChainMap.csv
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
